import type { ChatMessage, ChatMessageCreateRequest, ChatSessionSummary, ContentBlock } from "@lovart.dofe/shared";
import type { NativeChatRepository } from "../../database/chat-repository.js";
import type { AuthenticatedUser } from "../../auth/sso-authenticator.js";
import type { ThreadService } from "./thread-service.js";
export class ChatServiceError extends Error { constructor(readonly code: "chat_error" | "session_not_found", message: string, readonly statusCode: number) { super(message); } }
export type ChatService = { listSessions(user: AuthenticatedUser, canvasId: string): Promise<ChatSessionSummary[]>; createSession(user: AuthenticatedUser, canvasId: string, title?: string): Promise<ChatSessionSummary>; updateSessionTitle(user: AuthenticatedUser, sessionId: string, title: string): Promise<void>; deleteSession(user: AuthenticatedUser, sessionId: string): Promise<void>; listMessages(user: AuthenticatedUser, sessionId: string): Promise<ChatMessage[]>; createMessage(user: AuthenticatedUser, sessionId: string, input: ChatMessageCreateRequest): Promise<ChatMessage> };
export function createChatService(options: { repository: NativeChatRepository; threadService: Pick<ThreadService, "createThreadId"> }): ChatService { return {
  async listSessions(user, canvasId) { const sessions = await options.repository.listSessions(user.id, canvasId); if (!sessions) throw new ChatServiceError("chat_error", "Failed to list sessions.", 500); return sessions.map((s) => ({ id: s.id, title: s.title, updatedAt: s.updated_at.toISOString() })); },
  async createSession(user, canvasId, title) { const session = await options.repository.createSession(user.id, canvasId, options.threadService.createThreadId(), title); if (!session) throw new ChatServiceError("chat_error", "Failed to create session.", 500); return { id: session.id, title: session.title, updatedAt: session.updated_at.toISOString() }; },
  async updateSessionTitle(user, sessionId, title) { if (!await options.repository.updateTitle(user.id, sessionId, title)) throw new ChatServiceError("session_not_found", "Session not found.", 404); },
  async deleteSession(user, sessionId) { if (!await options.repository.deleteSession(user.id, sessionId)) throw new ChatServiceError("session_not_found", "Session not found.", 404); },
  async listMessages(user, sessionId) { const messages = await options.repository.listMessages(user.id, sessionId); if (!messages) throw new ChatServiceError("session_not_found", "Session not found.", 404); return dedupe(messages.map(mapMessage)); },
  async createMessage(user, sessionId, input) { const message = await options.repository.createMessage(user.id, sessionId, { content: input.content, contentBlocks: input.contentBlocks ?? null, role: input.role, toolActivities: input.toolActivities ?? null }); if (!message) throw new ChatServiceError("session_not_found", "Session not found.", 404); return mapMessage(message); },
}; }
function mapMessage(row: { content: string; content_blocks: unknown[] | null; created_at: Date; id: string; role: "user" | "assistant"; tool_activities: unknown[] | null }): ChatMessage { const blocks = Array.isArray(row.content_blocks) && row.content_blocks.length ? row.content_blocks as ContentBlock[] : legacy(row.content, row.tool_activities); return { content: row.content, contentBlocks: blocks, createdAt: row.created_at.toISOString(), id: row.id, role: row.role, toolActivities: row.tool_activities as ChatMessage["toolActivities"] }; }
function legacy(content: string, activities: unknown[] | null): ContentBlock[] | null { const blocks: ContentBlock[] = []; if (content) blocks.push({ type: "text", text: content }); for (const item of activities ?? []) blocks.push({ type: "tool", ...(item as any) }); return blocks.length ? blocks : null; }
function dedupe(messages: ChatMessage[]) { return messages.filter((message, index) => index === 0 || message.role !== messages[index - 1]!.role || message.content !== messages[index - 1]!.content); }
